code --install-extension ban.spellright
code --install-extension dracula-theme.theme-dracula
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sleistner.vscode-fileutils
code --install-extension vscodevim.vim
code --install-extension wingrunr21.vscode-ruby
