#!/bin/bash

function usage() {
  echo notes 
  echo "usage: echo pocket o w"
  echo "o -> pocket, feedly, keep"
  echo "w -> workspace number"
  echo example: pocket 5
}

if [ -z "$1" ] || [ -z "$2" ]; then
  usage
  exit
fi

declare -A urls=(["pocket"]="https://getpocket.com/a/queue/" ["feedly"]="https://feedly.com/i/index" ["keep"]="https://keep.google.com/")
declare -A diagrams=(["pocket"]="link_flow_diagram.png" ["feedly"]="link_flow_diagram.png" ["keep"]="keep_flow_diagram.png")
url="${urls[$1]}"
diagram="${diagrams[$1]}"

workspace=$2

i3-msg "workspace $workspace; append_layout /home/mfranc/layouts/notes.json"

termite -d $HOME/notes/ &
termite -d $HOME/notes/ &
xviewer ~/images/$diagram &
google-chrome --new-window $url &
