#!/bin/bash

function usage() {
  echo notes 
  echo "usage: echo pocket o w"
  echo "o -> pocket, feedly, keep"
  echo "w -> workspace number"
  echo example: pocket 5
}

if [ -z "$1" ] || [ -z "$2" ]; then
  usage
  exit
fi

declare -A urls=(["pocket"]="https://getpocket.com/a/queue/" ["feedly"]="https://feedly.com/i/index" ["keep"]="https://keep.google.com/")
url="${urls[$1]}"

workspace=$2

i3-msg "workspace $workspace; append_layout /home/mfranc/layouts/notes.json"

termite -d $HOME/notes/ &
termite & 
google-chrome --new-window $url
