#!/bin/bash

data=$(</dev/stdin)"\n---------------------------"

if [ $# -eq 0 ]; then
  echo -e "$data" >> ~/notes/twitter.md  
  echo -e "$data" >> ~/notes/newsletter.md  
  echo note sent to twitter and newsletter
  exit
fi

if [ -z "$1" ]; then
  echo -e "$data" >> ~/notes/twitter.md  
  echo note sent to twitter
fi

if [ -z "$2" ]; then
  echo -e "$data" >> ~/notes/newsletter.md
  echo note sent to newsletter
fi
