#!/bin/bash

function usage() {
  echo planning
  echo "planning:  w"
  echo "w -> workspace number"
  echo example: planning
}

if [ -z "$1" ]; then
  usage
  exit
fi

workspace=$1

i3-msg "workspace $workspace; append_layout /home/mfranc/layouts/planning.json"

google-chrome --new-window https://miro.com &
nvim -n ~/todo.work/projects/planning.md &
termite -d ~/ &
xviewer ~/images/planning.png &
google-chrome --new-window https://calendar.google.com/calendar/r &
