#!/bin/bash

function usage() {
  echo code
  echo "usage: social w"
  echo "w -> workspace number"
  echo example: social 5
  echo
  echo Opens up a layout with typical social media things
}

if [ -z "$1" ]; then
  usage
  exit
fi

workspace=$1

i3-msg "workspace $workspace; append_layout /home/mfranc/layouts/social.json"

google-chrome --new-window https://tweetdeck.twitter.com/ https://news.ycombinator.com/ https://outlook.office365.com/owa/ https://discordapp.com/ &
slack &

if [ -x "$(command -v zoom)" ]; then
  zoom &
else
  termite &
fi
