#!/bin/bash

# script to start test that run on file change

function autotest() {
  if  [[ $1 == 'python' ]]; then
    rg --files -tpy | entr python3 -m unittest
  fi

  if  [[ $1 == 'rust' ]]; then
    rg --files -trust | entr cargo test -- --nocapture
  fi

  if  [[ $1 == 'bash' ]]; then
    rg --files -tsh | entr bats $2
  fi

  if  [[ $1 == 'go' ]]; then
    rg --files -tgo | entr go test $2
  fi
}
