#!/bin/bash

BACKLIGHT="/sys/class/backlight/intel_backlight/brightness"

set_brightness() {
  local level=$1
  local xbright=$2
  if [ -f "$BACKLIGHT" ]; then
    echo "$level" | sudo tee "$BACKLIGHT"
  fi
  for output in $(xrandr --listmonitors | awk 'NR>1 {print $NF}'); do
    xrandr --output "$output" --brightness "$xbright"
  done
}

if [ "$1" == "low" ]; then
  set_brightness 40000 0.85
elif [ "$1" == "vvlow" ]; then
  set_brightness 4000 0.7
elif [ "$1" == "vlow" ]; then
  set_brightness 10000 0.7
else
  set_brightness 70000 1
fi

