#!/bin/bash


if [ "$1" == "low" ]; then
  echo 40000 | sudo tee /sys/class/backlight/intel_backlight/brightness
  xrandr --output DP-1 --brightness 0.85
  xrandr --output DP-2 --brightness 0.85
elif [ "$1" == "vlow" ]; then
  echo 10000 | sudo tee /sys/class/backlight/intel_backlight/brightness
  xrandr --output DP-1 --brightness 0.7
  xrandr --output DP-2 --brightness 0.7
else
  xrandr --output DP-1 --brightness 1
  xrandr --output DP-2 --brightness 1
  echo 100000 | sudo tee /sys/class/backlight/intel_backlight/brightness
fi

