#!/bin/bash

echo checking if qualys running
ps -U root | grep 'qualys'
systemctl | grep qualys

echo check if qualys is making correct connections
apt-cache show qualys-cloud-agent | grep Version
echo ---------------------------

echo checking if alien vault running
ps -U root | grep 'osquery'
systemctl | grep osquery
echo ---------------------------

echo checking if antivirus running
ps -U root | grep 'savd'
systemctl | grep 'sav.protect'
echo ---------------------------

