#!/bin/bash

# creates documents for projects base on context
# TODO:
# docs . opens documentation based on currenct folder context
# docs x open specified docuemntation

context=$(task _get rc.context)
project=$(tdir)
pick=$1

# docs list all the available documentations
if [ "$pick" = "" ]; then
  echo displaying available docs
  ls ~/todo.work/projects
  exit
fi

if [ "$pick" = "." ]; then
    mkdir ~/todo.work/projects/$project
    nvim ~/todo.work/projects/$project/README.md
    exit
fi

nvim ~/todo.work/projects/$pick/README.md
