#!/bin/bash

# creates documents for projects base on context

context=$(task _get rc.context)
project=$(tdir)
if [ "$context" = "form3" ] || [ "$context" = "workfocus" ]; then
  vim ~/Work/docs/$project.md
else
  mkdir ~/notes/projects/$project
  vim ~/notes/projects/$project/README.md
fi
