#!/bin/bash
declare -A dogsLimit
dogsLimit['confused']=4

if [ ! -v dogsLimit[$1] ]; then
  echo $1 not supported - at the moment only consumed dogs are supported
  exit
fi

randDog=$((1 + $RANDOM % ${dogsLimit[$1]}))

echo https://raw.githubusercontent.com/michal-franc/JustDogs/main/confused$randDog.gif | xclip -selection clipboard
