#!/bin/bash

# script for taking quick not
file=~/Work/notes/quicknotes.md


if [[ $# -eq 0 ]] ; then
  cat $file | tail
else
  if [[ "$1" == "nvim" ]] ; then
    nvim $file
  else
    echo "- $@" >> $file
  fi
fi 
