#!/bin/bash

current_remote=$(git remote get-url origin)
new_remote=${current_remote//github.com/github.com-michal-franc}

git remote remove origin
git remote add origin $new_remote

git config user.signingkey D601B52A09CB37801C683B977B3513AA7AE99621
git config user.email lam.michal.franc@gmail.com

