#!/bin/bash

# display all the prs from the child repos of master folder
# requires hub

function prlist() {
  for d in `ls -d */`
  do
    echo $d
    pushd $d > /dev/null
    hub pr list -f '%sC%>(8)%i%Creset - %t %sC%au%Creset%n %sC%>(8)%Creset %sC%>(4)link%Creset %U%n%n'
    popd > /dev/null
  done
}
