#!/bin/bash

new_name=$1


if [ $# -eq 0 ]
then
  echo rename current layout script
  echo usage rename-current-workspace 'name'
else
  current_name="$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name')"
  current_no_quote="$(echo $current_name | cut -d"\"" -f2)"

  current_number=${current_no_quote:0:1}

  command="rename workspace $current_name to \"$current_number: $current_number:$new_name\""

  i3-msg $command
fi
