#!/bib/bash

# script to save images in Pictures or in currect folder with specified name

if [[ $# -eq 0 ]] ; then
  maim --noopengl -s -d 1 ~/Pictures/$(date +%s).png
else
  maim --noopengl -s -d 1 $PWD/$@
fi 
