#!/bin/bash

# uses main to take screenshot
# put it in .folder
# put it to clipboard ready for markdown paste

folder="/home/michal-franc/.local/share/Anki2/User 1/collection.media"
fileName="anki-$(date +%s).png"
fileAndFolderName="${folder}/$fileName"
maim --noopengl -s -d 1 "$fileAndFolderName"
echo "<img src=\"${fileName}\">" | xclip -selection clipboard
echo Created file $fileAndFolderName and put it to clipboard
echo use ctrl + v in your editor
