#!/bin/bash  

# alias for taskwarriors that works with project based on git repo
clear
dir=$(tdir)

# set context to current context or empty
context="+$(task _get rc.context)"

if [ "$context" = "+" ] || [ "$context" = "+home" ]; then
  context=""
fi

if [ "$dir" = "$USER" ]; then
  task $context $@
  exit
fi

# situation when we are in todo.work folder then we assume we deal with projects
if [ "$dir" = "todo.work" ]; then
  baseproject=$(basename "`pwd`")

  # override context if project has its own context
  if [ -f context.md ]; then
    context="+$(head -n 1 context.md )"
  fi

  task '(urgency > 0)' pro:$baseproject $context $@
  exit
fi

task '(urgency > 0)' pro:$dir $context  $@
