#!/bin/bash  

# alias for taskwarriors that works with project based on git repo

dir=$(tdir)

if [ "$dir" = "$USER" ]; then
  dir=
fi

context=$(task _get rc.context)
if [ "$context" = "form3" ]; then
  task +$context pro:$dir $@
elif [ "$context" = "workfocus" ]; then
  task +form3 +today  pro:$dir $@
elif [ "$context" = "homefocus" ]; then
  task +today pro:$dir $@
else
  task pro:$dir $@
fi
