#!/bin/bash  

# alias for taskwarriors that works with project based on git repo

dir=$(tdir)

context=$(task _get rc.context)
if [ "$context" = "form3" ]; then
  echo "$@" | xargs -L1 task add +$context pro:$dir
elif [ "$context" = "workfocus" ]; then
  echo "$@" | xargs -L1 task add +today +form3 pro:$dir
elif [ "$context" = "homefocus" ]; then
  echo "$@" | xargs -L1 task add +today pro:$dir
else
  echo "$@" | xargs -L1 task add pro:$dir $@
fi
