#!/bin/bash

# create dir for other functions
# so that /blog -> pro:blog
# if .git repo will use .git base folder

# check if this folder is inside git repo 
$(git rev-parse --is-inside-work-tree > /dev/null 2>&1)

# check if previous command failed
# (if its not repo there is a fatal error)
if [ $? -eq 0 ]; then
  dir=$(basename $(git rev-parse --show-toplevel))
  
  # check if this is main folder (as dotfiles .git)
  # or todo folder as this one is used for my tasks
  if [ $dir = $(basename ~) ] || [ $dir = 'todo' ] || [ $dir = 'notes' ]; then
    # if its dotfiles folder go to pwd
    dir=$(basename $PWD)
  fi
else
  dir=$(basename $PWD)
fi
echo $dir
