#!/bin/bash  
clear

if [ $# -eq 0 ]
then
  task status:pending and +today modify -today +stash
  echo stashed current +today tatsks
elif [ "$1" == "pop" ]
then
  task status:pending and +stash modify -stash +today
  echo restored stashed tasks to +today
fi
