#!/bin/bash

# Script for syncing my todo list

# git add -> commit -> pull -> auto merge and push
function tsync() {
  pushd ~/todo
    git add -A
    git commit -m 'syncing todo'
    git pull origin master --no-edit
    git push origin master
  popd
}
