#!/bin/bash

# script for quick worklog creation
file=~/Work/mfranc-work/worklog.md

if [[ $# -eq 0 ]] ; then
  cat $file | tail
else
  if [[ "$1" == "nvim" ]] ; then
    nvim $file
  else
    echo "- $@" >> $file
  fi
fi 
